name: failedWorkflow
run-name: ${{ github.actor }} is testing out GitHub Actions, this time how to make a job failing depending on the result 🚀

on:
  workflow_dispatch:

jobs:
  Runtime-of-Solution-on-Github-runner:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout_Repo
        uses: actions/checkout@v4

      - name: Run_test_application
        id: run_test
        run: |
          cd src
          kotlinc test.kt -include-runtime -d test.jar
          output=$(java -jar -Xss1024m test.jar)
          echo "result=$output" >> $GITHUB_ENV

      - name: Check output
        if: env.result != '42'
        run: |
          echo "The output is not 42, failing the job."
          exit 1
