name: failedWorkflow
run-name: ${{ github.actor }} is testing out GitHub Actions, this time how to make a job failing depending on the result 🚀

on:
  workflow_dispatch:

jobs:
  Runtime-of-Solution-on-Github-runner:
    runs-on: RJPlog_selfHosted
    steps:

      - name: Checkout_Repo
        uses: actions/checkout@v4

      - name: Run_test_application
        id: run_test
        run: |
          cd src
          kotlinc test.kt -include-runtime -d test.jar
          output=$(java -jar -Xss1024m test.jar)
          echo "result=$output" >> $GITHUB_ENV

      - name: Set PRECHECKSTATUS
        run: |
          if [ "$result" == "42" ]; then
            echo "PRECHECKSTATUS=0" >> $GITHUB_ENV
          elif [ "$result" == "43" ]; then
            echo "PRECHECKSTATUS=1" >> $GITHUB_ENV
          else
            echo "PRECHECKSTATUS=2" >> $GITHUB_ENV
          fi

      - name: Output PRECHECKSTATUS
        run: echo "PRECHECKSTATUS=$PRECHECKSTATUS"

      - name: Check PRECHECKSTATUS
        if: env.PRECHECKSTATUS != '0'
        run: |
          echo "PRECHECKSTATUS is not 0, failing the job."
          exit 1
