name: IssueDemo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  issues:
    types: [opened]
jobs:
  Explore-GitHub-Actions-Issus:
    runs-on: ubuntu-latest
    steps:
      - name: give notification
        run:  |
          echo "An issue was filed by ${{ github.actor }} event."
          echo "new issue" > issue.txt
        
      - name: uplad file
        uses: actions/upload-artifact@v1
        with:
          name: issue.txt 




      

 
