name: IssueDemo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  issues:
    types: [opened]
jobs:
  Explore-GitHub-Actions-Issus:
    runs-on: ubuntu-latest
    steps:
      - run: echo "An issue was filed by ${{ github.actor }} event."
      - run: echo "new issue" > issue.txt
     # - uses: actions/checkout@v3
     # - run: git checkout -b "test"
     # - run: git push
