name: GitHub Actions Demo Create File
run-name: ${{ github.actor }} is testing out GitHub Actions, this time create a file
on: push
permissions:
  contents: write
jobs:
  Create-File-with-Time-Stamps-for-Every-Push-and-Commit:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Build SW   
        run: |
          echo "Build SW - not needed but for testing reasons still in"
          kotlinc -Werror src/hello.kt -include-runtime -d hello.jar
      - name: Add date to File
        run: |
          date "+%H:%M:%S   %d/%m/%y" >> new_file.txt
          ls ${{ github.workspace }}
      - name: Commit File
        run: |
          git config --global user.name 'RJPlog'
          git config --global user.email 'tfrenz67@gmail.com'
          git add new_file.txt
          git commit -m "Automated report"
          git push

      - name: Build SW out of different repos's
        run: |
          kotlinc -Werror aoc2024/day2401_1_2.kt -include-runtime -d day2401_1_2.jar
          kotlinc -Werror aoc2023/day2301_1_2.kt -include-runtime -d day2301_1_2.jar
          
      - name: Run application
        run: |
          java -jar day2401_1_2.jar
          java -jar day2301_1_2.jar
          echo "🍏 This job's status is ${{ job.status }}."
