name: Checkout2Repos
run-name: ${{ github.actor }} is testing out GitHub Actions, this time to build how to check out multiple repositories 🚀

on:
  workflow_dispatch:

jobs:
  Checkout_2_different_repositories:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout first year
        uses: actions/checkout@v4
        with:
          repository: RJPlog/aoc-2024
          path: aoc

      - name: Checkout second year
        uses: actions/checkout@v4
        with:
          repository: RJPlog/aoc-2023
          path: aoc

      - name: show content
        run: ls ${{ github.workspace }}
