name: Checkout2Repos
run-name: ${{ github.actor }} is testing out GitHub Actions, this time to build how to check out multiple repositories 🚀

on:
  workflow_dispatch:

jobs:
  Checkout_2_different_repositories:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout first year
        uses: actions/checkout@v4
        with:
          repository: RJPlog/aoc-2024
          path: aoc2024

      - name: Checkout second year
        uses: actions/checkout@v4
        with:
          repository: RJPlog/aoc-2023
          path: aoc2023

      - name: show content
        run: |
          ls -R ${{ github.workspace }}

      - name: Build SW out of different repos's
        run: |
          kotlinc -Werror aoc2024/day2401_1_2.kt -include-runtime -d aoc2024/day2401_1_2.jar
          kotlinc -Werror aoc2023/day2301_1_2.kt -include-runtime -d ao2023/day2301_1_2.jar
          
      - name: Run application
        run: |
          java -jar aoc2024/day2401_1_2.jar
          java -jar aoc2023/day2301_1_2.jar
          echo "🍏 This job's status is ${{ job.status }}."
